-- Insert an owner to test for an owner with no reservation -- 
INSERT INTO HVK_OWNER O
(O.OWNER_NUMBER, O.OWNER_FIRST_NAME, O.OWNER_LAST_NAME, O.OWNER_STREET, O.OWNER_CITY, O.OWNER_PROVINCE, O.OWNER_POSTAL_CODE, O.OWNER_PHONE, O.OWNER_EMAIL, O.EMERGENCY_CONTACT_FIRST_NAME, O.EMERGENCY_CONTACT_LAST_NAME, O.EMERGENCY_CONTACT_PHONE, O.VET_VET_NUMBER)
VALUES
(HVK_OWNER_SEQ.NEXTVAL, 'Cody', 'Berube', '123 Fake St', 'Gatineau', 'QC', 'J8Z3L4', '1231231234', 'example@gmail.com', NULL, NULL, NULL, 1);

--------------------------------------------------------------------------------

-- insert reservations so that all runs are occupied -- 

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-SEP-17', 'DD-MON-YY'), TO_DATE('20-SEP-17', 'DD-MON-YY'));

--------------------------------------------------------------------------------

-- insert reservations so that all large runs are occupied but other runs are available --

-- OCCUPY RUN 21 --
INSERT INTO HVK_RESERVATION R 
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE) 
VALUES 
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-OCT-17', 'DD-MON-YY'), TO_DATE('30-OCT-17', 'DD-MON-YY'));

INSERT INTO HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
29,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
21
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);

-- OCCUPY RUN 22 --
INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-OCT-17', 'DD-MON-YY'), TO_DATE('30-OCT-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
33,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
22
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);

-- OCCUPY RUN 28 --
INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-OCT-17', 'DD-MON-YY'), TO_DATE('30-OCT-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
31,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
28
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);

-- OCCUPY RUN 13 --
INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-OCT-17', 'DD-MON-YY'), TO_DATE('30-OCT-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
12,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
13
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);

-- OCCUPY RUN 14 --
INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-OCT-17', 'DD-MON-YY'), TO_DATE('30-OCT-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
16,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
14
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);

-- OCCUPY RUN 27 --
INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('15-OCT-17', 'DD-MON-YY'), TO_DATE('30-OCT-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
3,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
27
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);


-- INSERT A RESERVATION TO TEST THE CANCEL METHOD --
INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('10-DEC-17', 'DD-MON-YY'), TO_DATE('11-DEC-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
3,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
27
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);

-- INSERT A RESERVATION THAT WILL BE ACTIVE WHEN DELETED --
INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('01-APR-17', 'DD-MON-YY'), TO_DATE('31-AUG-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
3,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
27
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);

-- INSERT A RESERVATION WITH 2 PET RESERVATIONS TO TEST REMOVING ONE PET --
INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('10-DEC-17', 'DD-MON-YY'), TO_DATE('11-DEC-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
11,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
27
);

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
12,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
27
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);

-- INSERT A RESERVATION TO CAUSE A CONFLICT -- 
INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('02-DEC-17', 'DD-MON-YY'), TO_DATE('04-DEC-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
11,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
27
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);

INSERT INTO HVK_RESERVATION R
(R.RESERVATION_NUMBER, R.RESERVATION_START_DATE, R.RESERVATION_END_DATE)
VALUES
(HVK_RESERVATION_SEQ.NEXTVAL, TO_DATE('05-DEC-17', 'DD-MON-YY'), TO_DATE('07-DEC-17', 'DD-MON-YY'));

INSERT INTO
HVK_PET_RESERVATION(
PET_RES_NUMBER,
PET_PET_NUMBER,
RES_RESERVATION_NUMBER,
PR_SHARING_WITH,
RUN_RUN_NUMBER
)
VALUES(
HVK_PET_RES_SEQ.NEXTVAL,
11,
HVK_RESERVATION_SEQ.CURRVAL,
NULL,
27
);

INSERT INTO HVK_PET_RESERVATION_SERVICE
(SERVICE_FREQUENCY, PR_PET_RES_NUMBER, SERV_SERVICE_NUMBER)
VALUES
(NULL, HVK_PET_RES_SEQ.CURRVAL, 1);